

# Site Settings
title: 						"Заметки Ворона"
email: 						"sergey@voron.pw"
description: 				"Обо всем, что мне интересно"
baseurl: 					""
url: 						"http://vorons.github.io"
logourl: 					"/assets/img/bloglogo.jpg"		
fa-logo: 					"fa-bookmark-o"
paginate: 					5


# Author Settings
author_name: 				"Сергей Ворон"
author_url: 				"http://voron.pw"
author_bio: 				""
author_email: 				"sergey@voron.pw"
author_image: 				"/assets/img/authorimage.jpg"


# Social Settings
twitter_url: 				"http://twitter.com"
facebook_url: 				"http://facebook.com"
github_url:  				"http://github.com"
youtube_url:  				"http://youtube.com"
dribbble_url:  				"http://dribbble.com"
googleplus_url: 			"http://google.com/plus"
instagram_url:  			"http://instagram.com"
pinterest_url:  			"http://pinterest.com"
linkedin_url:  				"http://linkedin.com"


# Theme Settings
theme_disqus_shortname: 	"ecko"
theme_google_comments: 		false
theme_analytics_id: 		""
theme_analytics_domain: 	"voron.pw"
theme_reading_time: 		true
theme_autoload_comments: 	false
theme_always_show_nav: 		false


# SASS Settings
# DO NOT MODIFY
sass:
 sass_dir: "assets/css/"
 style: :compressed


# Build Settings
markdown: 					kramdown
permalink: 					pretty

